spring.application.name=notificacao-service

#RABBITMQ CONFIG
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

#RABBITMQ CUSTOM CONFIG
rabbitmq.exchange.name=pedidos.v1.pedido-criado
rabbitmq.exchange.dlx.name=pedidos.v1.pedido-criado.dlx

rabbitmq.queue.name=pedidos.v1.pedido-criado-gerar-notificacao
rabbitmq.queue.dlq.name=pedidos.v1.pedido-criado-gerar-notificacao.dlq

spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.retry.enable=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry,initial-interval=5s
spring.rabbitmq.listener.simple.retry.multiplier=2

spring.rabbitmq.listener.simple.message-converter=jackson

#spring email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=brayan.iub10@gmail.com
spring.mail.password=xoaz ycek mgxr pfgw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true