spring.application.name=notificacao-service

#RABBITMQ CONFIG
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

#RABBITMQ CUSTOM CONFIG
rabbitmq.exchange.name=pedidos.v1.pedido-criado

rabbitmq.queue.name=pedidos.v1.pedido-criado-gerar-notificacao

spring.rabbitmq.listener.simple.message-converter=jackson

#spring email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=brayan.iub10@gmail.com
spring.mail.password=xoaz ycek mgxr pfgw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true