spring.application.name=pedidos-api
server.port=8081

# CONFIGURACAO CORE DO SWAGGER

# 1. Caminho para a TELA VISUAL (Interface grafica para testar)
springdoc.swagger-ui.path=/swagger-ui.html

# 2. Caminho para o JSON BRUTO (Onde ele esta lendo agora)
springdoc.api-docs.path=/api-docs

# 3. Pacote dos seus controllers
springdoc.packagesToScan=br.com.sistemasbas.pedidos.api.controller


#RABBITMQ CONFIG
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

#RABBITMQ CUSTOM CONFIG
rabbitmq.exchange.name=pedidos.v1.pedido-criado